### ISSUE TITLE
Disable logging of sensitive information in production and add a warning to the UI in case that fails

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#102]
```
        NotificationCenter.default.publisher(for: .qrZaddressScanned)
                ...
                logger.debug("got address \(address)")
```

This could be a privacy leak if logs are left around and the user expects everything to be gone after nuking. This might not be the only instance, there are probably others.

If these logs are helpful for development/debugging then it would be nice to have build options to disable them with some UI warnings if they're enabled, like https://github.com/zcash/zcash-android-wallet/issues/122.

**Comment by pacu** [comment]
@defuse we have different targets for building with or without logging. would that be enough to close this?

**Comment by defuse** [comment]
Yes if building without logging is the "default" (i.e. you need to do something extra, like setting an environment variable or passing a command-line option, to get the logging build).

**Comment by pacu** [comment]
They are totally separate targets in the build system; you need to choose
one. There's no "default one"
```

xcodebuild -workspace ECC-Wallet.xcworkspace

xcodebuild: error: If you specify a workspace then you must also specify a
scheme.  Use -list to see the schemes in this workspace.
```

**Comment by defuse** [comment]
Oh, that's good! I just realized what I originally wanted was a warning in the UI like for android: https://github.com/zcash/zcash-android-wallet/issues/122 I'll update this title's ticket.

**Comment by pacu** [comment]
@geffenz, I think we need a screen for this.

**Comment by geffenz** [comment]
Thanks for the heads-up! On it!

**Comment by pacu** [comment]
Logging level can be modified by developers or avoided completely by choosing the no logging target
