### ISSUE TITLE
Make toSeed validate the seed phrase first

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#105]
```
    func toSeed(mnemonic: String) -> [UInt8]? {
        guard let data = Mnemonic.deterministicSeedBytes(from: mnemonic) else { return nil }
        return [UInt8](data)
    }
```

This `toSeed` function should validate the seed first. This is very low priority, since I checked the BIP39 library we're using and it does validate the seed internally, but having a redundant check here wouldn't hurt (avoids bugs in case we ever switch out the library).

The corresponding androidissue is https://github.com/zcash/zcash-android-wallet/issues/120.

**Comment by pacu** [comment]
now is validated 
```
   func toSeed(mnemonic: String) throws -> [UInt8] {
        let data = try Mnemonic.deterministicSeedBytes(from: mnemonic)
        return [UInt8](data)
    }
```
