### ISSUE TITLE
Warn in UI if crashlytics is enabled

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#106]
This is the same as the android issue https://github.com/zcash/zcash-android-wallet/issues/122.

There's a tradeoff here between protecting user privacy and being able to investigate crashes (which might indicate security bugs), so this is open for discussion.

A production release of this app should probably not include any kind of automated crash reporting, since (a) secrets like the seed may be visible in the stack trace or memory dumps, and (b) even if the crash report contains no secrets, it could still leak information about what the user is doing both to the developers who have access to the crash reports and to anyone observing the network traffic (they'd learn that a crash occurred by noticing a spike in bandwidth, so if they knew what was likely to crash, they'd learn what the user was likely doing).

A useful safeguard to put in place, on top of having build options that easily disable crashlytics for production deployments, would be to have the app display a big red warning screen upon opening whenever crashlytics is enabled. This way devs can use crashlytics for internal/private testing but if they ever accidentally ship it in a release it'll be very obvious and the mistake will be corrected quickly.

**Comment by pacu** [comment]
We included the no-logging target to cover this case.
