### ISSUE TITLE
Wallet History Icons and Colors Match Revised tx detail screen

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#121]
The new iconography and color palette for the revised tx detail screen should be bubbled up to the wallet history screen as well.

![image](https://user-images.githubusercontent.com/484008/114464398-17c6e600-9bbc-11eb-9184-a89cb11fabcc.png)

Stretch Goal full-redesign.
[walletdetails.pdf](https://github.com/zcash/zcash-ios-wallet/files/6299894/walletdetails.pdf)

**Comment by geffenz** [comment]
Closed as it applies to the legacy wallet.
