### ISSUE TITLE
[Disconnect handling] App does not reconnect after loosing connection

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-ios-wallet#137]
upon failing to connect to lightwalletd, the app retries the connection MAX_RETRIES times and then is stuck. 

It should:

- provide proper messaging
- allow the user to keep retrying
- reconnect properly if app is backgrounded and foregrounded.

Note:  this fix will require changes both on the SDK and Wallet

**Comment by Monteveeno** [comment]
can you send the code so i can fix this issue

**Comment by pacu** [comment]
Sorry @Monteveeno I'm not following you, could you please elaborate so I can help you better?
