### ISSUE TITLE
iOS Error Handling

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#157]
Improve error handling in iOS

Tasks:
- [x] Log errors to MixPanel
- [x] Surface descriptive errors to user
- [ ] Reach parity with Android for error handling

Time Box: 8 hours

**Comment by pacu** [comment]
- Update sending screen, logged errors to mix panel, fixed animations and odd buttons
- fixed QRScanning errors, improved QR scanner feedback 
- improved wallet history. logged errors to mixpanel
- fixed bug where history would sometimes be cleared
- modified the way transaction details were shown
- implemented own nav bar
- improved authentication errors
- added minedheight to details
