### ISSUE TITLE
Research Spike: Background Sync

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#169]
Research on how to add background syncing to the iOS wallet and create tickets for work. 

@LarryRuane: Research on Lightwalletd normal http requests for downloading ranges of compact blocks
Time box: 2 hours

**Comment by pacu** [comment]
Houston, we have a problem. Background fetch is done specifically from URLSession tasks, not custom blocks of code. 

I created a question on Swift GRPC project regarding this https://github.com/grpc/grpc-swift/issues/955

@LarryRuane can LWD be called with a classic HTTP request?

**Comment by pacu** [comment]
We need further info on whether gRPC can work with URLSession or if we need to do something

**Comment by LarryRuane** [comment]
See also https://github.com/zcash/lightwalletd/issues/305

**Comment by lindanlee** [comment]
iOS part is done, this ticket is now only tracking the work in #305. Mark as duplicate and will close.
