### ISSUE TITLE
toSeed should throw when it fails instead of returning nil

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#176]
https://github.com/zcash/zcash-ios-wallet/blob/49517b746d6ee600b5e3451d1e0ed38c648b3334/wallet/wallet/Utils/MnemonicSeedPhraseProvider.swift#L25-L28

If it returns nil, then nil will be passed to importSeed here:

https://github.com/zcash/zcash-ios-wallet/blob/49517b746d6ee600b5e3451d1e0ed38c648b3334/wallet/wallet/Views/RestoreWallet.swift#L47-L55

librustzcash should catch this if it happens, but it would be an improvement if it were clear nothing bad could happen from the Swift code alone

**Comment by pacu** [comment]
Implemented in #178

**Comment by defuse** [comment]
This is fixed.
