### ISSUE TITLE
Localization for iOS

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-ios-wallet#177]
As a developer, I'd like to work with the iOS SDK and have all text in the app match the user's locale.

Criteria
For each supported language (English, Spanish, simplified Chinese, Russian):
- [ ] Each screen in the app only contains words in that language
- [x] Layouts are not broken for the most common screen sizes
- [x] (optional, prioritize all other localization first) number, date and time formats match the locale (this is deceptively complex for the number entry fields)

Implementation details
- [ ] all text from all screens is pulled out of layout files and code and put into `strings.xml` for localization **[3 pts]**
- [ ] date/time formatters should be modified for proper localization support **[3 pts]**
- [ ] (optional, prioritize all other localization first) currency formatter should either support each locale or be consistent for all locales. The former probably takes a lot of effort and is prone to bugs. **[3 pts]**

**Comment by gmale** [comment]
Copied over verbiage from [the Android counterpart ](https://github.com/zcash/zcash-android-wallet/issues/200)

**Comment by pacu** [comment]
@geffenz  I've noticed we are missing some screens and features:

- Nuke wallet 
- send confirmation screen
  - it's missing an error state which says "unable to send"
  - it's missing the "includes memo" legend with the checkmark
- Transaction details
- Scan QR
 - probably need to sync up around camera authorization cases (unauthorized, authorization request)

**Comment by pacu** [comment]
Scan address current texts

````
//ScanAddress
"Request Camera Access" = "Request Camera Access";
"We don't have permission to access your camera" = "We don't have permission to access your camera";
"Camera Unavailable" = "Camera Unavailable";
"Switch to your Zcash address" = "Switch to your Zcash address";
"This QR Code does not contain a Zcash valid address!" = "This QR Code does not contain a Zcash valid address!";`
````

**Comment by pacu** [comment]
we don't have labels for "share address" and "Receive ZEC" on receive screens

**Comment by geffenz** [comment]
Added all notes to master.

Added chinese to master.

**Comment by lindanlee** [comment]
We're missing ~10 phrases for translations which is preventing progress.

**Comment by lindanlee** [comment]
Marking this as done for now, will create a new ticket to fill in the missing translation phrases. If missing, the text falls back to English.

**Comment by pacu** [comment]
missing strings 
"label_add_memo" = "Add Memo Here (optional)";
"scan_invalidQR" = "This QR Code does not contain a Zcash valid address!";
"label_includesmemo" = "Includes Memo";
"label_unabletosend" = "Unable to send";
"wallet_history_sent" = "Sent";
