### ISSUE TITLE
Canopy upgrade integration test

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#196]
Create a test for the upgrade from Heartwood to Canopy on testnet in the ECC Wallets. Canopy activates on testnet at block 1028500

Criteria:
- [ ] Send and receive funds before and after
- [ ] Wallet remains active through upgrade

**Comment by pacu** [comment]
test created but fails
- [ ] testSpendPriorFundsAfterActivation
- [ ] testSpendPostActivationFundsAfterConfirmation
- [ ] testSpendMinedSpendThatExpiresOnActivation
- [ ] testExpiredSpendAfterActivation
- [ ] testCombinePreActivationNotesAndPostActivationNotesOnSpend

test created and succeeds
- [ ] testSpendPriorFundsAfterActivation
- [ ] testSpendPostActivationFundsAfterConfirmation
- [ ] testSpendMinedSpendThatExpiresOnActivation
- [ ] testExpiredSpendAfterActivation
- [ ] testCombinePreActivationNotesAndPostActivationNotesOnSpend

**Comment by gmale** [comment]
Related Android issue: https://github.com/zcash/zcash-android-wallet/issues/210
