### ISSUE TITLE
It's also worth noting that it is not sufficient to canonicalize the public keys before passing them to libsodium signature validation, because:

### ISSUE THREAD

**Issue by jess22664** [zcash/zcash-ios-wallet#205]
It's also worth noting that it is not sufficient to canonicalize the public keys before passing them to libsodium signature validation, because:

* there is no way to canonicalize small-order points in a way that would be accepted by libsodium; and
* libsodium 1.0.15 hashes the public key as originally encoded when computing the hash internal to Ed25519.

_Originally posted by @daira in https://github.com/zcash/zcash/issues/2872#issuecomment-577226539_

**Comment by daira** [comment]
I'm not sure what the context of this is. Doesn't the iOS wallet use zcash_primitives?

**Comment by pacu** [comment]
Can you provide more context @jess22664 ? Also, if so, this ticket should be opened in ZcashLightClientKey, the zcash sdk
