### ISSUE TITLE
Biometrics locked

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash-ios-wallet#219]
Yesterday my thumb was wet so the fingerprint-recogniser didn't recognize it three times in a row, and then there was an error message that said something like "biometrics locked". Now today I can't pay at all: "Authorization failed! Fallback authentication mechanism selected."

(Related: https://github.com/zcash/zcash-ios-wallet/issues/217 in which I advocate that we not have this authorization step at all.)

**Comment by braddmiller** [comment]
Assessment: biometric authorization fails without a backup option to use a pin which causes a failure and inability to send.
Priority: Medium
