### ISSUE TITLE
Send screen says "enter shielded address" when it can accept t and z

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-ios-wallet#241]
it should read: "Enter a valid Zcash Address"

note: please update localizations too

**Comment by gmale** [comment]
<img src="https://user-images.githubusercontent.com/1699841/110350432-b54d5980-8001-11eb-8d40-a87b16049499.jpg" width=390/>

**Comment by gmale** [comment]
Note: Once localization is updated, Android can switch to using this value. This is one place where it is currently using a non-localized string because the localized version didn't match the UI.
