### ISSUE TITLE
Balance Testing

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#86]
As a developer I would like to be able to verify the presence and accuracy of balance details.

Scaffolding:
- [x] Verify available balance is correct in all wallet states during a send
- [x] Verify total balance in all wallet states during a send
- [x] Verify incoming transactions
- [x] Verify change transactions
- [x] Verify transactions that expire are reflected accurately in balance

Test actually run:
Requirements:
- [ ] Verify available balance is correct in all wallet states during a send
- [ ] Verify total balance in all wallet states during a send
- [ ] Verify incoming transactions
- [ ] Verify change transactions
- [ ] Verify transactions that expire are reflected accurately in balance

Master Wallet Testing Doc with Pseudocode for tests:
https://docs.google.com/document/d/1Kv53ZnH_NVvP-b-6zMnZSCFk3k8sD-VlyGp40LMHczM/edit#

**Comment by pacu** [comment]
This is done on BalanceTests suite on the SDK. The problem is librustzcash not displaying the right amount after sending for 10 confirmations.
