### ISSUE TITLE
Implement new send flow without t-address capabilities

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#93]
Implement the new send flow without adding t-address capabilities. This includes revising the send screen and revisions to the address screen.

Requirements:
- [ ] Send flow follows new designs (8)
- [x] Address screen is changed to follow new design WITHOUT t-addresses (yet) (5)
- - [x] Address screen removes access to the camera
- - [x] Address screen adds a share button to the bottom
- - [x] Add "This is your shielded Zcash address [Copy Icon]"

@geffenz Please attach those designs here.

Acceptance Criteria: 
- [ ] Implemented design is accepted by Geffen re: original designs

**Comment by pacu** [comment]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/b5852506-7c7c-4c15-a2bf-6d50c3ad4ebf)
