### ISSUE TITLE
iOS Send Feedback

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#95]
Implement a basic feedback capture form

- [ ] Rank your experience (1-5)
- [ ] Any detail you'd like to share (text field)
- [ ] Was your balance clear (text field)
- [ ] What feature would you like to see next (text field)
- [ ] Submits results to mixpanel

**Comment by gmale** [comment]
Here is a [link to where this is done on Android](https://github.com/zcash/zcash-android-wallet/blob/762eff533bd5717ebbf3874cc99d0a11556c2ad6/app/src/main/java/cash/z/ecc/android/ui/profile/FeedbackFragment.kt#L69):

**Comment by geffenz** [comment]
![Screenshot_20200707-093709.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/12603db6-3deb-496d-b638-996eb0ea39c4)
