### ISSUE TITLE
Information might be lost when memos are truncated due to reply addresses

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-ios-wallet#98]
It looks like the code will silently truncate the memo (i.e. delete information the user expects will be in the memo) if it's too long when a reply address is included:

```
    static func includeReplyTo(address: String, in memo: String, charLimit: Int = SendFlowEnvironment.maxMemoLength) -> String {
        
        let replyTo = "\nfrom \(address)"
        
        if (memo.count + replyTo.count) >= charLimit {
            let truncatedMemo = String(memo[memo.startIndex ..< memo.index(memo.startIndex, offsetBy: (memo.count - replyTo.count))])
            
            return truncatedMemo + replyTo
        }
        return memo + replyTo
        
    }
```

This could lead to accidental information loss / confusion. Not really a security issue. I haven't had a chance to use the app to see if there's an indication in the UI.

Also,

```
    static let maxMemoLength: Int = 255
```

Can be increased since memos can hold 512 bytes (but be careful that the first byte is used to indicate the format).

**Comment by pacu** [comment]
@defuse we modified this to the "reply to" option take the available chars quota in the UI instead. would that be good to close this issue ?
